package nemofrl.nemoapi.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WpPostsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public WpPostsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPostAuthorIsNull() {
			addCriterion("post_author is null");
			return (Criteria) this;
		}

		public Criteria andPostAuthorIsNotNull() {
			addCriterion("post_author is not null");
			return (Criteria) this;
		}

		public Criteria andPostAuthorEqualTo(Long value) {
			addCriterion("post_author =", value, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorNotEqualTo(Long value) {
			addCriterion("post_author <>", value, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorGreaterThan(Long value) {
			addCriterion("post_author >", value, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorGreaterThanOrEqualTo(Long value) {
			addCriterion("post_author >=", value, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorLessThan(Long value) {
			addCriterion("post_author <", value, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorLessThanOrEqualTo(Long value) {
			addCriterion("post_author <=", value, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorIn(List<Long> values) {
			addCriterion("post_author in", values, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorNotIn(List<Long> values) {
			addCriterion("post_author not in", values, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorBetween(Long value1, Long value2) {
			addCriterion("post_author between", value1, value2, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostAuthorNotBetween(Long value1, Long value2) {
			addCriterion("post_author not between", value1, value2, "postAuthor");
			return (Criteria) this;
		}

		public Criteria andPostDateIsNull() {
			addCriterion("post_date is null");
			return (Criteria) this;
		}

		public Criteria andPostDateIsNotNull() {
			addCriterion("post_date is not null");
			return (Criteria) this;
		}

		public Criteria andPostDateEqualTo(Date value) {
			addCriterion("post_date =", value, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateNotEqualTo(Date value) {
			addCriterion("post_date <>", value, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateGreaterThan(Date value) {
			addCriterion("post_date >", value, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateGreaterThanOrEqualTo(Date value) {
			addCriterion("post_date >=", value, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateLessThan(Date value) {
			addCriterion("post_date <", value, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateLessThanOrEqualTo(Date value) {
			addCriterion("post_date <=", value, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateIn(List<Date> values) {
			addCriterion("post_date in", values, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateNotIn(List<Date> values) {
			addCriterion("post_date not in", values, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateBetween(Date value1, Date value2) {
			addCriterion("post_date between", value1, value2, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateNotBetween(Date value1, Date value2) {
			addCriterion("post_date not between", value1, value2, "postDate");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtIsNull() {
			addCriterion("post_date_gmt is null");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtIsNotNull() {
			addCriterion("post_date_gmt is not null");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtEqualTo(Date value) {
			addCriterion("post_date_gmt =", value, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtNotEqualTo(Date value) {
			addCriterion("post_date_gmt <>", value, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtGreaterThan(Date value) {
			addCriterion("post_date_gmt >", value, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtGreaterThanOrEqualTo(Date value) {
			addCriterion("post_date_gmt >=", value, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtLessThan(Date value) {
			addCriterion("post_date_gmt <", value, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtLessThanOrEqualTo(Date value) {
			addCriterion("post_date_gmt <=", value, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtIn(List<Date> values) {
			addCriterion("post_date_gmt in", values, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtNotIn(List<Date> values) {
			addCriterion("post_date_gmt not in", values, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtBetween(Date value1, Date value2) {
			addCriterion("post_date_gmt between", value1, value2, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostDateGmtNotBetween(Date value1, Date value2) {
			addCriterion("post_date_gmt not between", value1, value2, "postDateGmt");
			return (Criteria) this;
		}

		public Criteria andPostStatusIsNull() {
			addCriterion("post_status is null");
			return (Criteria) this;
		}

		public Criteria andPostStatusIsNotNull() {
			addCriterion("post_status is not null");
			return (Criteria) this;
		}

		public Criteria andPostStatusEqualTo(String value) {
			addCriterion("post_status =", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusNotEqualTo(String value) {
			addCriterion("post_status <>", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusGreaterThan(String value) {
			addCriterion("post_status >", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusGreaterThanOrEqualTo(String value) {
			addCriterion("post_status >=", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusLessThan(String value) {
			addCriterion("post_status <", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusLessThanOrEqualTo(String value) {
			addCriterion("post_status <=", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusLike(String value) {
			addCriterion("post_status like", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusNotLike(String value) {
			addCriterion("post_status not like", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusIn(List<String> values) {
			addCriterion("post_status in", values, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusNotIn(List<String> values) {
			addCriterion("post_status not in", values, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusBetween(String value1, String value2) {
			addCriterion("post_status between", value1, value2, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusNotBetween(String value1, String value2) {
			addCriterion("post_status not between", value1, value2, "postStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusIsNull() {
			addCriterion("comment_status is null");
			return (Criteria) this;
		}

		public Criteria andCommentStatusIsNotNull() {
			addCriterion("comment_status is not null");
			return (Criteria) this;
		}

		public Criteria andCommentStatusEqualTo(String value) {
			addCriterion("comment_status =", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotEqualTo(String value) {
			addCriterion("comment_status <>", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusGreaterThan(String value) {
			addCriterion("comment_status >", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusGreaterThanOrEqualTo(String value) {
			addCriterion("comment_status >=", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusLessThan(String value) {
			addCriterion("comment_status <", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusLessThanOrEqualTo(String value) {
			addCriterion("comment_status <=", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusLike(String value) {
			addCriterion("comment_status like", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotLike(String value) {
			addCriterion("comment_status not like", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusIn(List<String> values) {
			addCriterion("comment_status in", values, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotIn(List<String> values) {
			addCriterion("comment_status not in", values, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusBetween(String value1, String value2) {
			addCriterion("comment_status between", value1, value2, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotBetween(String value1, String value2) {
			addCriterion("comment_status not between", value1, value2, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusIsNull() {
			addCriterion("ping_status is null");
			return (Criteria) this;
		}

		public Criteria andPingStatusIsNotNull() {
			addCriterion("ping_status is not null");
			return (Criteria) this;
		}

		public Criteria andPingStatusEqualTo(String value) {
			addCriterion("ping_status =", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusNotEqualTo(String value) {
			addCriterion("ping_status <>", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusGreaterThan(String value) {
			addCriterion("ping_status >", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusGreaterThanOrEqualTo(String value) {
			addCriterion("ping_status >=", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusLessThan(String value) {
			addCriterion("ping_status <", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusLessThanOrEqualTo(String value) {
			addCriterion("ping_status <=", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusLike(String value) {
			addCriterion("ping_status like", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusNotLike(String value) {
			addCriterion("ping_status not like", value, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusIn(List<String> values) {
			addCriterion("ping_status in", values, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusNotIn(List<String> values) {
			addCriterion("ping_status not in", values, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusBetween(String value1, String value2) {
			addCriterion("ping_status between", value1, value2, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPingStatusNotBetween(String value1, String value2) {
			addCriterion("ping_status not between", value1, value2, "pingStatus");
			return (Criteria) this;
		}

		public Criteria andPostPasswordIsNull() {
			addCriterion("post_password is null");
			return (Criteria) this;
		}

		public Criteria andPostPasswordIsNotNull() {
			addCriterion("post_password is not null");
			return (Criteria) this;
		}

		public Criteria andPostPasswordEqualTo(String value) {
			addCriterion("post_password =", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordNotEqualTo(String value) {
			addCriterion("post_password <>", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordGreaterThan(String value) {
			addCriterion("post_password >", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("post_password >=", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordLessThan(String value) {
			addCriterion("post_password <", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordLessThanOrEqualTo(String value) {
			addCriterion("post_password <=", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordLike(String value) {
			addCriterion("post_password like", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordNotLike(String value) {
			addCriterion("post_password not like", value, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordIn(List<String> values) {
			addCriterion("post_password in", values, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordNotIn(List<String> values) {
			addCriterion("post_password not in", values, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordBetween(String value1, String value2) {
			addCriterion("post_password between", value1, value2, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostPasswordNotBetween(String value1, String value2) {
			addCriterion("post_password not between", value1, value2, "postPassword");
			return (Criteria) this;
		}

		public Criteria andPostNameIsNull() {
			addCriterion("post_name is null");
			return (Criteria) this;
		}

		public Criteria andPostNameIsNotNull() {
			addCriterion("post_name is not null");
			return (Criteria) this;
		}

		public Criteria andPostNameEqualTo(String value) {
			addCriterion("post_name =", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotEqualTo(String value) {
			addCriterion("post_name <>", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameGreaterThan(String value) {
			addCriterion("post_name >", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameGreaterThanOrEqualTo(String value) {
			addCriterion("post_name >=", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameLessThan(String value) {
			addCriterion("post_name <", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameLessThanOrEqualTo(String value) {
			addCriterion("post_name <=", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameLike(String value) {
			addCriterion("post_name like", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotLike(String value) {
			addCriterion("post_name not like", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameIn(List<String> values) {
			addCriterion("post_name in", values, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotIn(List<String> values) {
			addCriterion("post_name not in", values, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameBetween(String value1, String value2) {
			addCriterion("post_name between", value1, value2, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotBetween(String value1, String value2) {
			addCriterion("post_name not between", value1, value2, "postName");
			return (Criteria) this;
		}

		public Criteria andPostModifiedIsNull() {
			addCriterion("post_modified is null");
			return (Criteria) this;
		}

		public Criteria andPostModifiedIsNotNull() {
			addCriterion("post_modified is not null");
			return (Criteria) this;
		}

		public Criteria andPostModifiedEqualTo(Date value) {
			addCriterion("post_modified =", value, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedNotEqualTo(Date value) {
			addCriterion("post_modified <>", value, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGreaterThan(Date value) {
			addCriterion("post_modified >", value, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("post_modified >=", value, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedLessThan(Date value) {
			addCriterion("post_modified <", value, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedLessThanOrEqualTo(Date value) {
			addCriterion("post_modified <=", value, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedIn(List<Date> values) {
			addCriterion("post_modified in", values, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedNotIn(List<Date> values) {
			addCriterion("post_modified not in", values, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedBetween(Date value1, Date value2) {
			addCriterion("post_modified between", value1, value2, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedNotBetween(Date value1, Date value2) {
			addCriterion("post_modified not between", value1, value2, "postModified");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtIsNull() {
			addCriterion("post_modified_gmt is null");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtIsNotNull() {
			addCriterion("post_modified_gmt is not null");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtEqualTo(Date value) {
			addCriterion("post_modified_gmt =", value, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtNotEqualTo(Date value) {
			addCriterion("post_modified_gmt <>", value, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtGreaterThan(Date value) {
			addCriterion("post_modified_gmt >", value, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtGreaterThanOrEqualTo(Date value) {
			addCriterion("post_modified_gmt >=", value, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtLessThan(Date value) {
			addCriterion("post_modified_gmt <", value, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtLessThanOrEqualTo(Date value) {
			addCriterion("post_modified_gmt <=", value, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtIn(List<Date> values) {
			addCriterion("post_modified_gmt in", values, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtNotIn(List<Date> values) {
			addCriterion("post_modified_gmt not in", values, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtBetween(Date value1, Date value2) {
			addCriterion("post_modified_gmt between", value1, value2, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostModifiedGmtNotBetween(Date value1, Date value2) {
			addCriterion("post_modified_gmt not between", value1, value2, "postModifiedGmt");
			return (Criteria) this;
		}

		public Criteria andPostParentIsNull() {
			addCriterion("post_parent is null");
			return (Criteria) this;
		}

		public Criteria andPostParentIsNotNull() {
			addCriterion("post_parent is not null");
			return (Criteria) this;
		}

		public Criteria andPostParentEqualTo(Long value) {
			addCriterion("post_parent =", value, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentNotEqualTo(Long value) {
			addCriterion("post_parent <>", value, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentGreaterThan(Long value) {
			addCriterion("post_parent >", value, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentGreaterThanOrEqualTo(Long value) {
			addCriterion("post_parent >=", value, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentLessThan(Long value) {
			addCriterion("post_parent <", value, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentLessThanOrEqualTo(Long value) {
			addCriterion("post_parent <=", value, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentIn(List<Long> values) {
			addCriterion("post_parent in", values, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentNotIn(List<Long> values) {
			addCriterion("post_parent not in", values, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentBetween(Long value1, Long value2) {
			addCriterion("post_parent between", value1, value2, "postParent");
			return (Criteria) this;
		}

		public Criteria andPostParentNotBetween(Long value1, Long value2) {
			addCriterion("post_parent not between", value1, value2, "postParent");
			return (Criteria) this;
		}

		public Criteria andGuidIsNull() {
			addCriterion("guid is null");
			return (Criteria) this;
		}

		public Criteria andGuidIsNotNull() {
			addCriterion("guid is not null");
			return (Criteria) this;
		}

		public Criteria andGuidEqualTo(String value) {
			addCriterion("guid =", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotEqualTo(String value) {
			addCriterion("guid <>", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidGreaterThan(String value) {
			addCriterion("guid >", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidGreaterThanOrEqualTo(String value) {
			addCriterion("guid >=", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLessThan(String value) {
			addCriterion("guid <", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLessThanOrEqualTo(String value) {
			addCriterion("guid <=", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLike(String value) {
			addCriterion("guid like", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotLike(String value) {
			addCriterion("guid not like", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidIn(List<String> values) {
			addCriterion("guid in", values, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotIn(List<String> values) {
			addCriterion("guid not in", values, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidBetween(String value1, String value2) {
			addCriterion("guid between", value1, value2, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotBetween(String value1, String value2) {
			addCriterion("guid not between", value1, value2, "guid");
			return (Criteria) this;
		}

		public Criteria andMenuOrderIsNull() {
			addCriterion("menu_order is null");
			return (Criteria) this;
		}

		public Criteria andMenuOrderIsNotNull() {
			addCriterion("menu_order is not null");
			return (Criteria) this;
		}

		public Criteria andMenuOrderEqualTo(Integer value) {
			addCriterion("menu_order =", value, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderNotEqualTo(Integer value) {
			addCriterion("menu_order <>", value, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderGreaterThan(Integer value) {
			addCriterion("menu_order >", value, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("menu_order >=", value, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderLessThan(Integer value) {
			addCriterion("menu_order <", value, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderLessThanOrEqualTo(Integer value) {
			addCriterion("menu_order <=", value, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderIn(List<Integer> values) {
			addCriterion("menu_order in", values, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderNotIn(List<Integer> values) {
			addCriterion("menu_order not in", values, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderBetween(Integer value1, Integer value2) {
			addCriterion("menu_order between", value1, value2, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andMenuOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("menu_order not between", value1, value2, "menuOrder");
			return (Criteria) this;
		}

		public Criteria andPostTypeIsNull() {
			addCriterion("post_type is null");
			return (Criteria) this;
		}

		public Criteria andPostTypeIsNotNull() {
			addCriterion("post_type is not null");
			return (Criteria) this;
		}

		public Criteria andPostTypeEqualTo(String value) {
			addCriterion("post_type =", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeNotEqualTo(String value) {
			addCriterion("post_type <>", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeGreaterThan(String value) {
			addCriterion("post_type >", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeGreaterThanOrEqualTo(String value) {
			addCriterion("post_type >=", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeLessThan(String value) {
			addCriterion("post_type <", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeLessThanOrEqualTo(String value) {
			addCriterion("post_type <=", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeLike(String value) {
			addCriterion("post_type like", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeNotLike(String value) {
			addCriterion("post_type not like", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeIn(List<String> values) {
			addCriterion("post_type in", values, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeNotIn(List<String> values) {
			addCriterion("post_type not in", values, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeBetween(String value1, String value2) {
			addCriterion("post_type between", value1, value2, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeNotBetween(String value1, String value2) {
			addCriterion("post_type not between", value1, value2, "postType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeIsNull() {
			addCriterion("post_mime_type is null");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeIsNotNull() {
			addCriterion("post_mime_type is not null");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeEqualTo(String value) {
			addCriterion("post_mime_type =", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeNotEqualTo(String value) {
			addCriterion("post_mime_type <>", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeGreaterThan(String value) {
			addCriterion("post_mime_type >", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeGreaterThanOrEqualTo(String value) {
			addCriterion("post_mime_type >=", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeLessThan(String value) {
			addCriterion("post_mime_type <", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeLessThanOrEqualTo(String value) {
			addCriterion("post_mime_type <=", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeLike(String value) {
			addCriterion("post_mime_type like", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeNotLike(String value) {
			addCriterion("post_mime_type not like", value, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeIn(List<String> values) {
			addCriterion("post_mime_type in", values, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeNotIn(List<String> values) {
			addCriterion("post_mime_type not in", values, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeBetween(String value1, String value2) {
			addCriterion("post_mime_type between", value1, value2, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andPostMimeTypeNotBetween(String value1, String value2) {
			addCriterion("post_mime_type not between", value1, value2, "postMimeType");
			return (Criteria) this;
		}

		public Criteria andCommentCountIsNull() {
			addCriterion("comment_count is null");
			return (Criteria) this;
		}

		public Criteria andCommentCountIsNotNull() {
			addCriterion("comment_count is not null");
			return (Criteria) this;
		}

		public Criteria andCommentCountEqualTo(Long value) {
			addCriterion("comment_count =", value, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountNotEqualTo(Long value) {
			addCriterion("comment_count <>", value, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountGreaterThan(Long value) {
			addCriterion("comment_count >", value, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountGreaterThanOrEqualTo(Long value) {
			addCriterion("comment_count >=", value, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountLessThan(Long value) {
			addCriterion("comment_count <", value, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountLessThanOrEqualTo(Long value) {
			addCriterion("comment_count <=", value, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountIn(List<Long> values) {
			addCriterion("comment_count in", values, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountNotIn(List<Long> values) {
			addCriterion("comment_count not in", values, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountBetween(Long value1, Long value2) {
			addCriterion("comment_count between", value1, value2, "commentCount");
			return (Criteria) this;
		}

		public Criteria andCommentCountNotBetween(Long value1, Long value2) {
			addCriterion("comment_count not between", value1, value2, "commentCount");
			return (Criteria) this;
		}

		public Criteria andRssIdIsNull() {
			addCriterion("rss_id is null");
			return (Criteria) this;
		}

		public Criteria andRssIdIsNotNull() {
			addCriterion("rss_id is not null");
			return (Criteria) this;
		}

		public Criteria andRssIdEqualTo(String value) {
			addCriterion("rss_id =", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdNotEqualTo(String value) {
			addCriterion("rss_id <>", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdGreaterThan(String value) {
			addCriterion("rss_id >", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdGreaterThanOrEqualTo(String value) {
			addCriterion("rss_id >=", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdLessThan(String value) {
			addCriterion("rss_id <", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdLessThanOrEqualTo(String value) {
			addCriterion("rss_id <=", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdLike(String value) {
			addCriterion("rss_id like", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdNotLike(String value) {
			addCriterion("rss_id not like", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdIn(List<String> values) {
			addCriterion("rss_id in", values, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdNotIn(List<String> values) {
			addCriterion("rss_id not in", values, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdBetween(String value1, String value2) {
			addCriterion("rss_id between", value1, value2, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdNotBetween(String value1, String value2) {
			addCriterion("rss_id not between", value1, value2, "rssId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wp_posts
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 10 23:18:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}