package nemofrl.nemoapi.entity;

public class WpPostsWithBLOBs extends WpPosts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_content
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	private String postContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_title
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	private String postTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_excerpt
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	private String postExcerpt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.to_ping
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	private String toPing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.pinged
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	private String pinged;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_content_filtered
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	private String postContentFiltered;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_content
	 * @return  the value of wp_posts.post_content
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public String getPostContent() {
		return postContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_content
	 * @param postContent  the value for wp_posts.post_content
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public void setPostContent(String postContent) {
		this.postContent = postContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_title
	 * @return  the value of wp_posts.post_title
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public String getPostTitle() {
		return postTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_title
	 * @param postTitle  the value for wp_posts.post_title
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public void setPostTitle(String postTitle) {
		this.postTitle = postTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_excerpt
	 * @return  the value of wp_posts.post_excerpt
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public String getPostExcerpt() {
		return postExcerpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_excerpt
	 * @param postExcerpt  the value for wp_posts.post_excerpt
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public void setPostExcerpt(String postExcerpt) {
		this.postExcerpt = postExcerpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.to_ping
	 * @return  the value of wp_posts.to_ping
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public String getToPing() {
		return toPing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.to_ping
	 * @param toPing  the value for wp_posts.to_ping
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public void setToPing(String toPing) {
		this.toPing = toPing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.pinged
	 * @return  the value of wp_posts.pinged
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public String getPinged() {
		return pinged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.pinged
	 * @param pinged  the value for wp_posts.pinged
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public void setPinged(String pinged) {
		this.pinged = pinged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_content_filtered
	 * @return  the value of wp_posts.post_content_filtered
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public String getPostContentFiltered() {
		return postContentFiltered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_content_filtered
	 * @param postContentFiltered  the value for wp_posts.post_content_filtered
	 * @mbg.generated  Sat Aug 10 23:43:19 CST 2019
	 */
	public void setPostContentFiltered(String postContentFiltered) {
		this.postContentFiltered = postContentFiltered;
	}
}