package nemofrl.nemoapi.entity;

public class WpTermRelationshipsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationships.object_id
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    private Long objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_term_relationships.term_taxonomy_id
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    private Long termTaxonomyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_relationships.object_id
     *
     * @return the value of wp_term_relationships.object_id
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_relationships.object_id
     *
     * @param objectId the value for wp_term_relationships.object_id
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_term_relationships.term_taxonomy_id
     *
     * @return the value of wp_term_relationships.term_taxonomy_id
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    public Long getTermTaxonomyId() {
        return termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_term_relationships.term_taxonomy_id
     *
     * @param termTaxonomyId the value for wp_term_relationships.term_taxonomy_id
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    public void setTermTaxonomyId(Long termTaxonomyId) {
        this.termTaxonomyId = termTaxonomyId;
    }
}