package nemofrl.nemoapi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import nemofrl.nemoapi.entity.WpPosts;
import nemofrl.nemoapi.entity.WpPostsExample;
import nemofrl.nemoapi.entity.WpPostsWithBLOBs;
@Repository
public interface WpPostsMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	long countByExample(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int deleteByExample(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int insert(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int insertSelective(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	List<WpPostsWithBLOBs> selectByExampleWithBLOBs(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	List<WpPosts> selectByExample(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	WpPostsWithBLOBs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int updateByExampleSelective(@Param("record") WpPostsWithBLOBs record, @Param("example") WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") WpPostsWithBLOBs record, @Param("example") WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int updateByExample(@Param("record") WpPosts record, @Param("example") WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int updateByPrimaryKeySelective(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbg.generated  Mon Aug 12 12:32:11 CST 2019
	 */
	int updateByPrimaryKey(WpPosts record);

	int countByRssId(String rssId);
	
	int getId();
}