package nemofrl.nemoapi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import nemofrl.nemoapi.entity.WpTermRelationships;
import nemofrl.nemoapi.entity.WpTermRelationshipsExample;
import nemofrl.nemoapi.entity.WpTermRelationshipsKey;
@Repository
public interface WpTermRelationshipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    long countByExample(WpTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int deleteByExample(WpTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int deleteByPrimaryKey(WpTermRelationshipsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int insert(WpTermRelationships record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int insertSelective(WpTermRelationships record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    List<WpTermRelationships> selectByExample(WpTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    WpTermRelationships selectByPrimaryKey(WpTermRelationshipsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") WpTermRelationships record, @Param("example") WpTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int updateByExample(@Param("record") WpTermRelationships record, @Param("example") WpTermRelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int updateByPrimaryKeySelective(WpTermRelationships record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_term_relationships
     *
     * @mbg.generated Sun Aug 11 01:12:21 CST 2019
     */
    int updateByPrimaryKey(WpTermRelationships record);
}